--liquibase formatted sql

--changeset vantoniuc:create-tables
CREATE SCHEMA IF NOT EXISTS shop;
CREATE SCHEMA IF NOT EXISTS admin;

CREATE TABLE shop.categories (
    category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name VARCHAR(50) NOT NULL
);

CREATE TABLE shop.products (
    product_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name VARCHAR(100) NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    description TEXT,
    image BYTEA,
    category_id BIGINT NOT NULL,
    FOREIGN KEY (category_id) REFERENCES shop.categories(category_id)
);